### ISSUE TITLE
Android and other mobile device support

### ISSUE THREAD

**Issue by AlessioCorridori** [patrickchiang/obsidian-dialogue-mode#3]
Hi Patrick, this plugin is absolutely fantastic.
At the moment it only works on the desktop version (I use it on windows platform), is there a chance you could make it compatible for the Android version of Obsidian as well?

A small suggestion for improvement: in books, sometimes the characters « and » (Guillemets) are used instead of single or double quotes.
It would be great if it were possible to customise the dialogue delimiting characters in the plugin options.

Thank you very much

**Comment by patrickchiang** [comment]
I've made the changes: allow installing on mobile, added option to customize dialogue start/end characters, and added guillemets to the default list.

I did very light testing on mobile; surprisingly, it seems to work, but let me know if any bugs/issues come up.
